# Generated by Django 3.0.7 on 2020-06-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200607_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
